services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ods-backend
    ports:
      - "8000:8000"
    volumes:
      # Montar directorio de modelos para persistencia
      - ./etapa2/retrain_models:/app/etapa2/retrain_models
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ods-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ods-network
